// This file is auto-generated by Lovable. Do not modify it.

export const lovable = {
  auth: {
    signInWithOAuth: async (_provider: "google" | "apple", _opts?: { redirect_uri?: string; extraParams?: Record<string, string> }) => {
      return { error: new Error("OAuth sign-in is handled by the FastAPI backend and is disabled in the frontend client.") };
    },
  },
};
